eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-service.uri:http://127.0.0.1:8761}/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}